version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./backend:/backend
    env_file:
      - .envs/.development


  web: &web
    image: darient:1.0.0
    build:
      context: .
      dockerfile: ./compose/development/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .envs/.development
