version: '3'

services:
  web: &web
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: skeleton-web:1.0
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    restart: always
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    env_file: .envs/.staging
    stdin_open: true
    tty: true

  db:
    image: percona:8
    ports:
      - "3306:3306"
    env_file: .envs/.staging
