# Generated by Django 4.0.5 on 2022-09-19 20:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('Privado', 'Privado'), ('Gobierno', 'Gobierno')], max_length=100, verbose_name='Tipo')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fullname', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('birthdate', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Edad')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion de habitacion')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono')),
                ('type', models.CharField(choices=[('Natural', 'Natural'), ('Juridico', 'Juridico')], max_length=100, verbose_name='Tipo')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.bank', verbose_name='Banco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion del Credito')),
                ('min_pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pago Minimo')),
                ('max_pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pago Maximo')),
                ('month_deadline', models.PositiveIntegerField(verbose_name='Plazos')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('type', models.CharField(choices=[('Automotriz', 'Automotriz'), ('Hipotecario', 'Hipotecario'), ('Comercial', 'Comercial')], max_length=100, verbose_name='Tipo')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.client', verbose_name='Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
